### ISSUE TITLE
Cannot read property 'show' of undefined ?

### ISSUE THREAD

**Issue by keyurparalkar** [localz/react-native-searchbar#12]
Hi Team,

I am getting this error : 'Cannot read property 'show' of undefined' whenever I call the method this.searchBar.show().

sample code : 

```
                                            <Button transparent onPress={()=>this.searchBar.show()}>
					            <Icon style={styles.dehazeStyle} name="search"/>
						</Button>
						

						<SearchBar
						  ref={(ref) => this.searchBar = ref}
						  data={items}
						  handleResults={this._handleResults}
						  showOnLoad='true'
						/>	
```

screenShot: 

![untitled](https://cloud.githubusercontent.com/assets/14138515/23076213/72e1be90-f565-11e6-9455-854f1e51deac.png)

**Comment by daveols** [comment]
@keyurparalkar it would seem the search bar ref isn't being set for whatever reason. Hard to see without seeing the rest of your code. Could you provide a short, complete example of code which reproduces this?

Also perhaps try setting the ref to a string:
`ref='searchBar'`
then you can access it like `this.refs['searchBar'].show()`

**Comment by daveols** [comment]
@keyurparalkar assuming you figured this out? I'm going to close the issue.

**Comment by Jazz747** [comment]
Had a similair problem, this worked. (RN 0.45.1, searchbar 1.10.0)

```javascript
<TouchableOpacity
  onPress={() => { this.refs.searchBar.show() }}>
</TouchableOpacity>

...

<SearchBar
   ref='searchBar'
   ...
/>`
