### ISSUE TITLE
README Properties Markdown not formatted properly

### ISSUE THREAD

**Issue by terencehuynh** [localz/react-native-searchbar#18]
The markdown is not displaying the available properties correctly. Make things hard to read.

<img width="923" alt="screen shot 2017-03-21 at 11 12 38 am" src="https://cloud.githubusercontent.com/assets/1747517/24127264/5f75ea4a-0e27-11e7-9345-ce8cf1ff3b95.png">

**Comment by hugomd** [comment]
Fixed in #19
