### ISSUE TITLE
[Android] BackgroundColor, placeHolderTextColor and textColor are not changing

### ISSUE THREAD

**Issue by themakerman** [localz/react-native-searchbar#26]
Unable to set these components to hex value= '#6c1414' or constant values like 'red','green', etc

**Comment by daveols** [comment]
@themakerman I just tested and these props are working as expected for me.

Can you provide the code you are using, as well as the platform, platform version and React Native version?

**Comment by themakerman** [comment]
I figured it out. I was facing some problem on my local machine. Thanks though :)
