### ISSUE TITLE
How add custom style properties to to search bar  

### ISSUE THREAD

**Issue by iiitmahesh** [localz/react-native-searchbar#27]
How to add custom style properties to to search bar  
<SearchBar style={{.......}} />

I want to modify custom serach like below. Can anyone guide me how to achive this using **react-native-searchbar**

![image](https://cloud.githubusercontent.com/assets/13597781/25555171/c729aa20-2cfc-11e7-8acc-a9ecc13e1b1b.png)

**Comment by daveols** [comment]
@iiitmahesh you're probably better off writing your own one from scratch or using https://github.com/umhan35/react-native-search-bar.
