### ISSUE TITLE
results return as empty list after clearing search bar

### ISSUE THREAD

**Issue by ddeanto** [localz/react-native-searchbar#3]
This is happening to me when using the provided example code. Before typing anything into the search bar, all of the items are displayed, however, if I type into the search bar AND THEN clear it, nothing is displayed since an empty results array is returned. I would expect all of the items are returned after the search bar is cleared. Other than this, everything else seems to be working.

**Comment by ddeanto** [comment]
I don't know if this matters, but I am using this in an Android Emulator.

**Comment by daveols** [comment]
This does actually make sense to me, however I am reluctant to change the behaviour as it may break current implementations. Perhaps adding an `onClear` callback would allow you to update your list to display all results upon a clear? Open a PR if this works for you and I'll merge it in.

**Comment by ddeanto** [comment]
I will hopefully have time soon to implement an `onClear` callback. It would be nice

**Comment by daveols** [comment]
I agree! In the meantime I have just released your `autoCorrect` changes.

**Comment by daveols** [comment]
@ddeanto https://github.com/localz/react-native-searchbar/commit/8fe97ed317637d30be00beccaeb7cc1caec118ff solves this for you. Just add allDataOnEmptySearch to your props!

**Comment by ddeanto** [comment]
Thank you!
