### ISSUE TITLE
in your exmple there isnt no value for variable items provided. 

### ISSUE THREAD

**Issue by jpca999** [localz/react-native-searchbar#33]
Can you please help fix my code below so that it works ?  ( expo ) 

import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

import {
  TouchableOpacity,
} from 'react-native';

import SearchBar from 'react-native-searchbar';

export default class App extends React.Component {

    constructor(props) {
      super(props);
      this.state = {
        items,
        results: []
      };
      this._handleResults = this._handleResults.bind(this);
    }

    _handleResults(results) {
      this.setState({ results });
    }

render() {

    return (
      <View>
             <View style={{ marginTop: 110 }}>
               {
                 this.state.results.map((result, i) => {
                   return (
                     <Text key={i}>
                       {typeof result === 'object' && !(result instanceof Array) ? 'gold object!' : result.toString()}
                     </Text>
                   );
                 })
               }
               <TouchableOpacity onPress={() => this.searchBar.show()}>
                 <View style={{ backgroundColor: 'green', height: 100, marginTop: 50 }}/>
               </TouchableOpacity>
               <TouchableOpacity onPress={() => this.searchBar.hide()}>
                 <View style={{ backgroundColor: 'red', height: 100 }}/>
               </TouchableOpacity>
             </View>
             <SearchBar
               ref={(ref) => this.searchBar = ref}
               data={items}
               handleResults={this._handleResults}
               showOnLoad
             />
           </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

**Comment by daveols** [comment]
The items array was in the readme. I've added it to the example too.
