### ISSUE TITLE
Search bar is causing a very weird bug on unrelated views on Android

### ISSUE THREAD

**Issue by puelocesar** [localz/react-native-searchbar#34]
I was having a serious problem with React Native on Android.

Let's say I have the following render method:

    render() {
        let stuff = this.state.showStuff ? <Text style={styles.stuff}>Stuff</Text> : null

        return (
            <SearchBar
                    ref={(ref) => this.searchBar = ref}
                    handleSearch={ input => this.debounceSearch(input) }
                    onHide={ () => this.hideSearch() }
                    />

            <View>
                { stuff }
            </View>
        )
    }

Really simple. If I want to hide the "Stuff", I just call: 

    this.setState({ showStuff: false })

This works fine on iOS, but on Android, the view wasn't being removed at all!! So after a lot of trial and error, I discovered that simply removing SearchBar from my component solved the issue. But I still have no idea why SearchBar has anything to do with this problem.

**Comment by daveols** [comment]
Very strange. Have you tried rendering the `SearchBar` at the bottom of your render function view? Also it looks as though your render function is invalid -- having two sibling components.

**Comment by puelocesar** [comment]
Sorry, I don't know, I removed it from my project and did a simple search bar myself. Solved the issue for me..

**Comment by daveols** [comment]
Okay, I'll close the issue for now then
