### ISSUE TITLE
X button does not clear input

### ISSUE THREAD

**Issue by clementino36** [localz/react-native-searchbar#38]
When I enter some text in the input and then press the X button, the text disappears but once I start typing again, the text I had entered previously reappears and the text I'm currently typing comes after the previous one.
Concretly put:
Start typing "Hello" -> Input = "Hello" -> X button press -> Input = "" -> Start typing " world" -> Input = "Hello world".
Any clue ?

**Comment by daveols** [comment]
@clementino36 can you share a code example that reproduces this? It may be how you're saving the input.

**Comment by clementino36** [comment]
Hi, sorry for the late answer.

SearchBar component:

```javascript
<SearchBar
      style={{ width: '100%', height: 50, borderWidth: 5, borderColor: 'grey' }}
      placeholder={'Search for a vehicle'}
      ref={(ref) => this.searchBar = ref}
      data={vehicles}
      showOnLoad={true}
      onFocus={(input) => { setSearchResults(vehicles); }}
      onBack={() => {
           if (shouldGetEcoDriveReports) {
                Keyboard.dismiss();
                navigate('EcoDriveReport');
           }
           if (shouldGetEcoSummaries) {
                Keyboard.dismiss();
                navigate('Score');
           }
       }}
       handleResults={(results) => this.handleResults(results)}
       focusOnLayout={true}
       heightAdjust={-10}
       allDataOnEmptySearch={true}
       backButton={searchIcon}
       clearOnBlur={false}
/>
```

handleResults:

```javascript
handleResults(vehicles: IVehicle[]) {
        const { setSearchResults, appReducer: { searchResults } } = this.props;
        const text = this.searchBar.getValue().toLowerCase();
        const results = vehicles.filter((vehicle) => {
            let { name } = vehicle;
            name = name.toLowerCase();
            return (name.includes(text));
        });
        if (!_.isEqual(searchResults, results)) {
            setSearchResults(results);
        }
    }
```

**Comment by daveols** [comment]
Apologies also for the late reply!

I haven't managed to reproduce the issue you describe using the above code which leads me to believe the problem lies within your `setSearchResults` function which you haven't provided.

Please ensure you're using the latest version `@1.11.0`.

**Comment by clementino36** [comment]
No worries! 
My mistake was to call the `setSearchResults` method on the `onFocus` event of the `SearchBar`, I commented this line and it all seems to be fine now. I'm not sure why though, `setSearchResults` is just a redux action that saves the results...
Thanks for your time anyway! Cheers

**Comment by muizkhan27** [comment]
can you guys answer 82 ?
