### ISSUE TITLE
Importing error

### ISSUE THREAD

**Issue by Kyonru** [localz/react-native-searchbar#43]
After installing the component, I can not used, an error is thrown and crash the app. 

![image](https://user-images.githubusercontent.com/17935828/31464734-357dbcf8-aea0-11e7-8875-e9ad505fca33.png)

**Comment by nnanna3wp** [comment]
Hey, this is a problem with the react-native-vector-icons package react-native-searcbar uses. They are currently using version 3.0.0, while the latest is 4.4.2.
See below for instructions to fix your issue.

1. cd into your react-native project folder
2. npm install --save react-native-vector-icons
3. navigate into your node_modules folder
4. copy the react-native-vector-icons folder
5. navigate into the react-native-searchbar folder
6. open the node_modules folder & delete the react-native-vector-icons folder
7. paste the react-native-vector-icons folder you copied from your projects node_modules folder
8. navigate back into the react-native-searchbar folder
9. open packages.js, search for vector-icons and change 3.0.0 to 4.4.2

You should be good to go now. Thats what I did to solve my issue. Note that this is a temporary fix until the developers update their react-native-vector-icons package

**Comment by daveols** [comment]
Should be fixed in 1.13.0
