### ISSUE TITLE
Invariant Violation: Element type is invalid.

### ISSUE THREAD

**Issue by rjmohammad** [localz/react-native-searchbar#50]
Hello, 

I just updated my projected dependencies but the app crashes as soon as the view with Search Bar is loaded. I am greeted by the following error.

![image](https://user-images.githubusercontent.com/19753555/35426434-0f178974-0231-11e8-881b-2ff6f79896bd.png)

Dependencies version :
"react": "16.2.0",
"react-native": "0.52.1",
"react-native-search-bar": "3.3.1"

Your time and assistance is much appreciated.

Thanks!

**Comment by daveols** [comment]
Hi @rjmohammad, you are rendering an object instead of a renderable React type somewhere in your RestaurantSearch component.
