### ISSUE TITLE
Change back button for search icon, onCancel gets not called

### ISSUE THREAD

**Issue by adriancuco** [localz/react-native-searchbar#52]
Hi,
Just  Android.
I'd like to have searchbar icon and when showed the back icon, on press on it make it not visible.

1) I was unable to add a view in the icon parameter, just changing the icon properties

2) I understood that onCancel might get called when click on Back icon, but I didn't find were it gets called.

I think it's a bug on Android.

Thx

    "react": "16.0.0",
    "react-native": "0.51.0",
    "react-native-elements": "^0.19.0",
    "react-native-vector-icons": "^4.5.0",

**Comment by daveols** [comment]
This is not currently possible @adriancuco, feel free to open a PR that implements this behaviour.
