### ISSUE TITLE
react-native-searchbar slow on Android and IOS device

### ISSUE THREAD

**Issue by SujaYuga** [localz/react-native-searchbar#53]
Hi,

I am able to successfully use react-native-searchbar on Expo and it works great but on Android and IOS device the performance visibly reduced which would not be acceptable for users. It is actually very bad on Android that it takes 2 secs to show the searchbar on click of search icon and on IOS 1 sec to show the search bar. I am using the searchbar in conjunction with react navigation and react navigation header buttons package to invoke the searchbar on click of icon from header sections. Below is the code snippet.

import SearchBar from 'react-native-searchbar';
import HeaderButtons from 'react-navigation-header-buttons'

export default class FirstScreen extends Component {
    static navigationOptions = ({ navigation }) => {
        const params = navigation.state.params || {};
        return {
            headerTitle: "Hello 1",
            headerRight: (
                <HeaderButtons IconComponent={Icon} iconSize={23} color="white">
                    <HeaderButtons.Item title="Search" iconName="search" onPress={params.handleSearchBar} />
                    <HeaderButtons.Item title="select" onPress={() => console.warn('edit')} />
                </HeaderButtons>
            ),
            headerLeft: (
                <Button
                    onPress={() => navigation.navigate('MyModal')}
                    title="Menu"
                    color="white"
                />
            ),
            headerStyle: {
                backgroundColor: '#f4511e',
                //display: 'none',
              },
        };
    };

    componentWillMount() {
        this.props.navigation.setParams({ handleSearchBar: this._handleSearchBar });
    }

    _handleSearchBar = () => {
        console.log('before - ', this.state.toggleSearchBar);

        if (this.state.toggleSearchBar) {
            this.search.show();
        }
        else {
            this.search.hide();
        }

        this.setState({toggleSearchBar: !this.state.toggleSearchBar})
        console.log('after - ', this.state.toggleSearchBar);
    }

    _handleSearchBack = () => {
        console.log('before - ', this.state.toggleSearchBar);
        this.search.hide();
        this.setState({toggleSearchBar: !this.state.toggleSearchBar})
        console.log('after - ', this.state.toggleSearchBar);
    }

    _handleSearchResults(input){
        this.setState({title: input});
    }

    _handleClearText(){
        this.setState({title: ""});
        //console.log('inside handle clear ', this.state.title);
        this.search.clearText;
    }

    constructor(props){
        super(props)
        this.state = {
            toggleSearchBar: true,
...

**Comment by daveols** [comment]
Hi guys, please try the latest release which has some performance improvements.
