### ISSUE TITLE
How can I programatically set the input text (not placeholder)?

### ISSUE THREAD

**Issue by tinashe96** [localz/react-native-searchbar#55]
When I perform a search and redirect to a new screen, I would like to show the searchbar with whatever input was submitted from the previous screen.

**Comment by MosesEsan** [comment]
You can add the code below to the index.js file

  setValue = (input) => {
    this.setState({input});
  };

And call it using 

this.searchBar.setValue("text")

When I have the time, I will create a pull request

**Comment by tinashe96** [comment]
@MosesEsan works great, thanks!

**Comment by tinashe96** [comment]
@MosesEsan do you mind if I create a pull request?
