### ISSUE TITLE
Is posible change icons

### ISSUE THREAD

**Issue by crisys11** [localz/react-native-searchbar#6]
Material icons works fine in android but in IOS it is not consistent with IOS style guides

**Comment by avishayil** [comment]
#9 exposes some props to change the icons if you like.
I exposed the back button, but I can alter the PR to handle close icon as well, if it's necessary.

**Comment by daveols** [comment]
@crisys11 @crisys11 I have commented on #9 with my thoughts on this. Let me know what you think.

**Comment by daveols** [comment]
@crisys11 this is now possible via https://github.com/localz/react-native-searchbar/pull/10
