### ISSUE TITLE
How can i search for specific data ?

### ISSUE THREAD

**Issue by sunnynegi** [localz/react-native-searchbar#62]
Hi team great plugin.

I have one question regarding this plugin , how can i search for keywords like, here is my json
{
    "status": true,
    name: "sunny"
}
I want to search only specific data, like name,no status. How can i achieve this ?

**Comment by sunnynegi** [comment]
Any help on this issue, use specific tags for search ?

**Comment by gtjamesa** [comment]
You can pass a custom search function into the `handleSearch` prop

**Comment by daveols** [comment]
Hi @sunnynegi, as @gtjamesa has pointed out you can implement your own search function using `handleSearch`.
