### ISSUE TITLE
Turkish character problem

### ISSUE THREAD

**Issue by gundogduyakici** [localz/react-native-searchbar#63]
Hello there,
My problem is, I can not find the words that start with "İ" in capital letters.

`const items = [
  'Test',
  'İlker'  
];`

If I search İlker, it will not find it. 
Try this.

**Comment by daveols** [comment]
Hi @gundogduyakici.

I can't seem to reproduce this. Can you provide a code sample?

![screen shot 2018-06-04 at 10 30 05 pm](https://user-images.githubusercontent.com/10344370/40917513-f31af180-6846-11e8-9841-261ab80f6e9b.png)

**Comment by gundogduyakici** [comment]
caps lock off? or do not press the shift key

**Comment by daveols** [comment]
![screen shot 2018-06-04 at 11 27 42 pm](https://user-images.githubusercontent.com/10344370/40920139-02836db6-684f-11e8-815c-5d5acda47454.png)

Those are my only input options with an active Turkish keyboard. I can't paste the text either, nor can I insert it using `adb shell input text "İlker"`. Any other ideas as to how I can reproduce?

**Comment by gundogduyakici** [comment]
Try typing Turkish on the keyboard of the computer and try enter in there.

**Comment by daveols** [comment]
I'm not able to do that. Have you tested this on an actual device, not an emulator?
