### ISSUE TITLE
Show items on load

### ISSUE THREAD

**Issue by wcisco17** [localz/react-native-searchbar#67]
Hey I'm having trouble showing my items once my screen is loaded it only renders the search button and a blank screen. Once I type in the search box it renders my items successfully, I've been trying to show my items before I type in the text box anyway to do so? 

here is a piece of my code let me know if this helps! 

                              <SearchBar
                                  ref={(ref) => this.searchBar = ref}
                                  getValue={this._handleResults}
                                  data={VolunteerOrg}
                                  handleResults={this._handleResults}
                                  showOnLoad
                                  backgroundColor={'#FF1493'}
                                  color={'white'}
                                  hideBack={true}
                                  allDataOnEmptySearch={true}
                                />

**Comment by daveols** [comment]
Hey @wcisco17,

Depending on how your application logic is implemented, you could do something like:

```javascript
const data = [ ... your list of items ]
...
state = { resultsToShow: data }
render = () =>  <FlatList data={this.state.resultsToShow} />
```

I.e. set the results to all of your data initially in the component constructor or `componentDidMount`.

**Comment by wcisco17** [comment]
Thank you for your reply I fixed it a bit agap usuing the same concept!
