### ISSUE TITLE
Not able to get value of the search bar

### ISSUE THREAD

**Issue by khanof89** [localz/react-native-searchbar#68]
Following is the code which I am trying but it does not provide value of the search bar 

    <SearchBar
                    ref={(ref) => this.searchBar = ref}
                    data={items}
                    onSubmitEditing={this._performSearch}
                />

     _performSearch(query) {
        //let query = this.searchBar.getValue();
        // also tries this.searchBar.getValue();
        // query.getValue();
        console.log('PERFORM SEARCH FUNCTION ');
        console.log(query);
        /*APIHelpers.searchProducts(query).then((res) => {
                console.log(res);
            }
        ).catch(err => {
            console.log('error');
            console.log(err);
        });*/
    }

I request you to please update the read me with more elaborated usage, I am a beginner and got confused implementing.

**Comment by daveols** [comment]
@khanof89 I'm not sure why that isn't working for you. Note that `onSubmitEditing` will not pass your callback any params.
 
You could try maintaining a copy of the search bar input value in your component state, by using the `handleChangeText` prop, then using this value to search your API when the user presses search.
